apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakenrf-nnrf-nfm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fakenrf-nnrf-nfm
  template:
    metadata:
      labels:
        app: fakenrf-nnrf-nfm
    spec:
      containers:
      - image: ghcr.io/1dco/fakenrf-nnrf-nfm:v0.2
        name: fakenrf-nnrf-nfm
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: fakenrf-env-key
